# Generated by Django 5.1 on 2024-08-22 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenamesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='word_order',
            field=models.CharField(default='[]', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GameWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revealed', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codenamesapp.game')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codenamesapp.word')),
            ],
        ),
    ]
