# Generated by Django 5.1 on 2024-08-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codenamesapp', '0002_game_word_order_gameword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='words',
        ),
    ]
