# Generated by Django 5.1 on 2024-08-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenamesapp', '0003_remove_game_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='word_order',
            field=models.CharField(default='[]', max_length=200),
        ),
    ]
