# Generated by Django 5.1 on 2024-08-22 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenamesapp', '0004_alter_game_word_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameword',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamewords', to='codenamesapp.game'),
        ),
    ]
